### ISSUE TITLE
Add ENV variable support

### ISSUE THREAD

**Issue by KevinSayers** [nextflow-io/cwl2nxf#17]
Add parsing for environment variables from CWL this will then map to Nextflow variables of the style env.foo 

```
cwlVersion: v1.0
class: CommandLineTool
baseCommand: env
requirements:
  EnvVarRequirement:
    envDef:
      HELLO: $(inputs.message)
inputs:
  message: string
outputs: []
```
