### ISSUE TITLE
hints

### ISSUE THREAD

**Issue by KevinSayers** [nextflow-io/cwl2nxf#18]
Docker and ResourceRequirement hints parse correctly if they are in the format 

```
hints:
- class: ResourceRequirement
  coresMin: 2
  outdirMin: 1024
  ramMin: 4096
- class: DockerRequirement
  dockerPull: java:7-jdk
```

The CWL user guide shows the following format which should also be supported

```
hints:
  DockerRequirement:
    dockerPull:  java:7-jdk
```
